# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: postgresql
  encoding: unicode
  database: worker_playground_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: railsuser
  timeout: 5000

test:
  <<: *default
  database: worker_playground_test

production:
  <<: *default
  database: worker_playground_production
  username: example
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
